### ISSUE TITLE
Kali linux vmware error: This script doesn't work for lightdm display manager

### ISSUE THREAD

**Issue by Marco5dev** [kp300/BACKGROUND-LOGIN-SCREEN#9]
![image](https://github.com/kp300/BACKGROUND-LOGIN-SCREEN/assets/100785809/25de675a-eb79-4766-98d7-8e240013460e)

**Comment by programmingrelay** [comment]
it only works on gdm(Gnome Display Manager)

**Comment by Marco5dev** [comment]
> it only works on gdm(Gnome Display Manager)

bro this issue is opened since Oct 17, 2023
i don't care now for this but thanks
